wojciech@oxos.pl:
  name: Wojciech 
  token: xxxxxxxxxxxxxxxx
  
daniel@legendarymill.com:
  name: daniel 
  token: eebe7dd0892e7156266362498942a8a2
  
daniel@oxos.pl:
  name: daniel 
  token: eebe7dd0892e7156266362498942a8a2